[package]
name = "zecwallet-cli"
version = "1.4.0"
edition = "2018"

[dependencies]
rustyline = "5.0.2"
clap = "2.33"
log = "0.4"
log4rs = "0.8.3"
shellwords = "1.0.0"
json = "0.12.0"
http = "0.2"
byteorder = "1"
tiny-bip39 = "0.6.2"

zecwalletlitelib = { path = "../lib/" }

